/**
 * Deletes an asset from the current assets.
 *
 * @param varchar :p_cur_type     The asset type (css, images, js).
 * @param varchar :p_cur_base_dir The directory relative to project root to base dir of the asset.
 * @param varchar :p_cur_path     The relative path of the asset.

 * @type none
 */
delete from PLS_CURRENT
where cur_type     = :p_cur_type
and   cur_base_dir = :p_cur_base_dir
and   cur_path     = :p_cur_path
